# -*- coding: utf-8 -*-
"""Yolo_1_Object_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yof7OPq-x0_54Npl4XcVvAKQkcWqTvoJ
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()

# Run inference on an image with YOLO11n
!yolo predict model=yolo11n.pt source='https://ultralytics.com/images/zidane.jpg'

# Run inference on an image with YOLO11n
!yolo predict model=yolo11n.pt source='https://images.picxy.com/cache/2019/7/25/7cb6f63a656f23f38c4fff9a4cf219bc.jpg'