# -*- coding: utf-8 -*-
"""Yolo_3_Workout_Video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LfloYF-EkcBMeEbdukde4xF1fRIURM80
"""

!pip install ultralytics

import cv2
import ultralytics
from ultralytics import solutions
from ultralytics.utils.downloads import safe_download

!apt-get install -y ffmpeg  # for video writing properly
ultralytics.checks()

exercises_list = ["Legextension", "Legpress", "Squats", "Pushups"]

for exercise in exercises_list:
    safe_download(f"https://github.com/ultralytics/assets/releases/download/v0.0.0/{exercise}.demo.video.mp4")

cap = cv2.VideoCapture("/content/Pushups.demo.video.mp4")
assert cap.isOpened(), "Error reading video file"

# Video writer
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))
video_writer = cv2.VideoWriter("Pushups.demo.video.output.avi", cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

# Init AIGym
gym = solutions.AIGym(
    show=True,  # Display the frame
    kpts=[5, 7, 9],  # keypoints index of person for monitoring specific exercise, by default it's for pushup
    model="yolo11n-pose.pt",  # Path to the YOLO11 pose estimation model file
    line_width=4,  # Adjust the line width for bounding boxes and text display
    verbose=False,
)

# Process video
while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    results = gym(im0)  # monitor workouts on each frame
    video_writer.write(results.plot_im)  # write the output frame in file.

video_writer.release()

cap = cv2.VideoCapture("/content/Squats.demo.video.mp4")
assert cap.isOpened(), "Error reading video file"

# Video writer
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))
video_writer = cv2.VideoWriter("Squats.demo.video.output.avi", cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

# Init AIGym
gym = solutions.AIGym(
    show=True,  # Display the frame
    kpts=[5, 11, 13],  # keypoints index of person for monitoring specific exercise, by default it's for pushup
    model="yolo11m-pose.pt",  # Path to the YOLO11 pose estimation model file
    line_width=4,  # Adjust the line width for bounding boxes and text display
    verbose=False,
)

# Process video
while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    results = gym(im0)  # monitor workouts on each frame
    video_writer.write(results.plot_im)  # write the output frame in file.

video_writer.release()